# Generated by Django 4.1.2 on 2022-10-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
